version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: home_library_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: qwerty
      DATABASE_NAME: home_library_db
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  postgres_data: